import type { Metadata } from "next"
import "./globals.css"
import { Poppins, Roboto } from "next/font/google"
import "../style/embla.css"

const poppins = Poppins({
    subsets: ["latin-ext"],
    display: "swap",
    variable: "--poppins-font",
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    style: ["normal"],
})

const roboto = Roboto({
  subsets: ["vietnamese"],
  display: "swap",
  variable: "--roboto-font",
  weight: ["100",  "300", "400", "500",  "700",  "900"],
  style: ["normal"],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={roboto.className}>{children}</body>
        </html>
    )
}
